table bridge_opportunity_plant
	lineageTag: 0e05e023-f07f-4c48-89e7-5b0897211da9

	column OpportunityId
		dataType: string
		isHidden
		lineageTag: f3288dd5-b180-47e7-92b8-c1f933cd8577
		summarizeBy: none
		sourceColumn: OpportunityId

		annotation SummarizationSetBy = Automatic

	column PlantId
		dataType: string
		isHidden
		lineageTag: 62c68ef1-fd87-402e-b577-d1899ee423aa
		summarizeBy: none
		sourceColumn: PlantId

		annotation SummarizationSetBy = Automatic

	partition bridge_opportunity_plant = m
		mode: import
		queryGroup: 2_DataModel
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "bridge_opportunity_plant.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"OpportunityId", type text}, {"PlantId", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

