table dim_loss_reason
	lineageTag: 0639c5f0-da49-49d9-9ed0-791a8abc9b31

	column LossReason
		dataType: string
		lineageTag: 7c783c7d-4864-4af5-8526-0d7d7d626c7d
		summarizeBy: none
		sourceColumn: LossReason

		annotation SummarizationSetBy = Automatic

	column ReasonCategory
		dataType: string
		lineageTag: a47e36b0-8e38-4585-b6d9-38c281876fbc
		summarizeBy: none
		sourceColumn: ReasonCategory

		annotation SummarizationSetBy = Automatic

	partition dim_loss_reason = m
		mode: import
		queryGroup: 2_DataModel
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_loss_reason.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"LossReason", type text}, {"ReasonCategory", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

