table dim_order_type
	lineageTag: 50c4f5b0-a6c2-4717-9914-3596e98280c2

	column OrderType
		dataType: string
		lineageTag: 6a114003-105f-4b69-9c54-2ecf26ea2109
		summarizeBy: none
		sourceColumn: OrderType

		annotation SummarizationSetBy = Automatic

	column OrderTypeShort
		dataType: string
		lineageTag: 6e0d34b7-26e0-4073-acb6-7bc2803a6766
		summarizeBy: none
		sourceColumn: OrderTypeShort

		annotation SummarizationSetBy = Automatic

	partition dim_order_type = m
		mode: import
		queryGroup: 2_DataModel
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_order_type.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"OrderType", type text}, {"OrderTypeShort", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

