table dim_theater
	lineageTag: 25e803db-0213-44d5-868e-909387ac8625

	column Theater
		dataType: string
		lineageTag: 2525dc6b-c3ff-478b-9c20-a54d3c3adb6f
		summarizeBy: none
		sourceColumn: Theater

		annotation SummarizationSetBy = Automatic

	column TheaterSort
		dataType: int64
		formatString: 0
		lineageTag: 8c57bc51-5dd5-4342-aec8-464944d40ed3
		summarizeBy: sum
		sourceColumn: TheaterSort

		annotation SummarizationSetBy = Automatic

	partition dim_theater = m
		mode: import
		queryGroup: 2_DataModel
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_theater.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Theater", type text}, {"TheaterSort", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

