table dim_forecast_category
	lineageTag: 74f11764-ee95-48f6-84c9-2464d82e04bb

	column ForecastCategory
		dataType: string
		lineageTag: adfbe3bc-aab1-4615-a75b-05006f782f74
		summarizeBy: none
		sourceColumn: ForecastCategory
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 0a8f8e75-2866-4e39-ac27-8dff187e0f93
		summarizeBy: none
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition dim_forecast_category = m
		mode: import
		queryGroup: 2_DataModel
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_forecast_category.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ForecastCategory", type text}, {"SortOrder", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

