table dim_stage
	lineageTag: cd6cf7e3-83c5-4712-b68f-028037f4c719

	column StageName
		dataType: string
		lineageTag: 48fafda2-f6e0-48ad-ba14-fd33c17aff30
		summarizeBy: none
		sourceColumn: StageName
		sortByColumn: StageOrder

		annotation SummarizationSetBy = Automatic

	column StageOrder
		dataType: int64
		formatString: 0
		lineageTag: f4c36516-c4fd-45a4-b4ac-0e33c7f483f8
		summarizeBy: none
		sourceColumn: StageOrder

		annotation SummarizationSetBy = Automatic

	column IsClosed
		dataType: int64
		formatString: 0
		lineageTag: 81ff7a50-32bb-427b-810a-b766c38aebae
		summarizeBy: none
		sourceColumn: IsClosed

		annotation SummarizationSetBy = Automatic

	column IsWon
		dataType: int64
		formatString: 0
		lineageTag: 732a19b1-5b24-4633-b1b6-adc38db30520
		summarizeBy: none
		sourceColumn: IsWon

		annotation SummarizationSetBy = Automatic

	column DefaultForecastCategory
		dataType: string
		lineageTag: 4d9f10ae-51b7-44cb-ab49-6ead9c04b707
		summarizeBy: none
		sourceColumn: DefaultForecastCategory

		annotation SummarizationSetBy = Automatic

	partition dim_stage = m
		mode: import
		queryGroup: 2_DataModel
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_stage.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"StageName", type text}, {"StageOrder", Int64.Type}, {"IsClosed", Int64.Type}, {"IsWon", Int64.Type}, {"DefaultForecastCategory", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

